# -*- coding: utf-8 -*-
"""CleaningClinicalDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCD1LrHQgY-E23Y1WgG9JB8vvemeHQrc
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("heart.csv")

data.head()

missing_values = data.isnull().any(axis=1)
print("Rows with missing values:")
print(missing_values)

duplicates_rows = data[data.duplicated()]
print("Duplicate Rows:")
print(duplicates_rows)

data.dropna(axis=0,inplace=True)

data.drop_duplicates(inplace=True)